[project]
name = "testovie"
version = "0.1.0"
description = "Описание проекта"
dependencies = []
requires-python = ">=3.11"

[tool.ruff.lint]
extend-select = ["I"]

[tool.ruff.format]
quote-style = "double"
indent-style = "space"